language: node_js
node_js:
  - '8.10.0'
notifications:
  email: false # Disable all mail notifications
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=postgres
    - PGSCHEMA=celsus_core
after_script: npm run coverage
