service: celsus-core

plugins:
  - serverless-domain-manager # plugin for custom domain name management

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  memorySize: 1024
  region: eu-west-2
  stage: dev
  endpointType: REGIONAL
  profile: serverless-admin-profile
  # >>> Connection to RDS instance
  role: arn:aws:iam::671123374425:role/lambda-vpc-execution-role
  vpc:
    securityGroupIds:
      - sg-06c688947d175cf8d
    subnetIds:
      - subnet-a5cafae8
      - subnet-5cf05835
      - subnet-a8b456d2
  # <<< Connection to RDS instance
  environment:
    PGUSER: ${ssm:PG_USERNAME~true}
    PGPASSWORD: ${ssm:PG_PASSWORD~true}
    PGHOST: ${ssm:PG_HOSTNAME~true}
    PGPORT: ${ssm:PG_PORT~true}
    PGDATABASE: ${ssm:PG_DB_NAME~true}

custom:
  # >>> Custom domain name
  customDomain:
    domainName: celsus.isnan.eu
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional
    certificateName: '*.isnan.eu'
    hostedZoneId: ZWC66FN0XU6P9
  # <<< Custom domain name

functions:
  getLibraries:
    handler: handler.getLibraries
    name: get-libraries
    events:
      - http:
          path: api/v1/libraries
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:671123374425:userpool/eu-west-2_ocAf57dZ3
  postLibrary: 
    handler: handler.postLibrary
    name: post-libraries
    events:
      - http:
          path: api/v1/libraries
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:671123374425:userpool/eu-west-2_ocAf57dZ3

