service: celsus-core

plugins:
  - serverless-webpack
  - serverless-domain-manager

custom:
  config: ${file(./infra.json)}
  customDomain:
    domainName: 'api-celsus.isnan.eu'
    certificateArn: ${self:custom.config.certificate}
    hostedZoneId: ${self:custom.config.hostedZone}
    basePath: 'core'
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: edge
  webpack:
    webpackConfig: './build/webpack.base.config.js'
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'npm'

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  memorySize: 1024
  region: ${self:custom.config.region}
  stage: ${self:custom.config.environment}
  endpointType: EDGE
  profile: serverless-admin-profile
  timeout: 30
  # >>> Enable Gzip compression on AWS APi Gateway
  apiGateway:
    minimumCompressionSize: 1024 # in bytes
  # <<< Enable Gzip compression on AWS APi Gateway
  # >>> Lambda has to live in VPC in order to access RDS
  role: ${self:custom.config.lambdaExecutionRoleArn}
  vpc:
    securityGroupIds:
      - ${self:custom.config.coreStorageSecurityGroup} # To access the RDS instance
      - ${self:custom.config.mainVPCDefaultSecurityGroup} # To publish to SNS via the VPC Endpoint
    subnetIds:
      - ${self:custom.config.mainVPCSubnet2}
  # <<< Lambda has to live in VPC in order to access RDS
  environment:
    PGUSER: ${ssm:core_storage_username_${self:provider.stage}~true}
    PGPASSWORD: ${ssm:core_storage_password_${self:provider.stage}~true}
    PGHOST: ${ssm:core_storage_hostname_${self:provider.stage}~true}
    PGPORT: ${ssm:core_storage_port_${self:provider.stage}~true}
    PGDATABASE: ${ssm:core_storage_database_${self:provider.stage}~true}
    PGSCHEMA: ${ssm:core_storage_schema_${self:provider.stage}~true}
    REGION: ${self:custom.config.region}
    LOG_LEVEL: info

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**
    - scripts/**
    - run-local-postgres.sh
    - secrets.txt

functions:
  getLibraries:
    handler: src/handler.getLibraries
    name: get-libraries
    events:
      - http:
          path: v1/libraries
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  postLibrary:
    handler: src/handler.postLibrary
    name: post-library
    events:
      - http:
          path: v1/libraries
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  deleteLibrary:
    handler: src/handler.deleteLibrary
    name: delete-library
    events:
      - http:
          path: v1/libraries/{id}
          method: delete
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  getLibrary:
    handler: src/handler.getLibrary
    name: get-library
    events:
      - http:
          path: v1/libraries/{id}
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  getBooks:
    handler: src/handler.getBooks
    name: get-books
    events:
      - http:
          path: v1/books
          method: get
          request:
            parameters:
              querystrings:
                offset: false
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  deleteBook:
    handler: src/handler.deleteBook
    name: delete-book
    events:
      - http:
          path: v1/books/{id}
          method: delete
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  postBook:
    handler: src/handler.postBook
    name: post-book
    events:
      - http:
          path: v1/books
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.config.userPoolArn}
  handleMessages:
    handler: src/handler.handleMessages
    name: handle-core-messages
    events:
      - sqs:
          arn: ${self:custom.config.coreQueueArn}
          batchSize: 1
